### PR TITLE
Read the Add this file Microsoft...

### PR DESCRIPTION
**Pull request by ghost**
Please Microsoft, read my Add This text file, its a message for you guys on what I ask for, Im not asking for the file to be added to the main github page for MSEdge, This was the only way I could get this message to you guys hopefully...

### CODE REVIEW

**Comment by NitroRayZ** [comment]
@MSEdgeTeam please ready my message

**Comment by NitroRayZ** [comment]
if you cant, here is my message

Hello Microsoft,

I am very excited for the new Edge browser, as it is built of chrome which I mainly use...
As Ive seen, we'll be able to import our bookmarks, passwords, and more from the old edge and other browsers such as Chrome...

Ive seen people say "the way it looks is bad", "it needs features from the old Edge to be brought back"..

So if you were to change to layout or add edges old features, please please please add the option to disable certain features in the browser, and be able to choose layouts such as:

Chrome
>Selected

Microsoft Edge
>Default

on and on.. What im trying to say is, let us choose between the way the browser will look, if you do accept what I've said, I do plan on switching from Chrome to the new Edge, but if it has features that I dont need or like, and it dosent look anything like Chrome and is slower, I might not switch..

Thank you for your time...
- Rayford

**Comment by NitroRayZ** [comment]
Why was my Request Closed, did you read it? @molant

**Comment by molant** [comment]
@NitroRayZ yes, I read your PR.

> This document exists to clarify our thinking on how that work will proceed: we want to explain our plans and intentions related to Microsoft Edge and the Chromium open-source project.

To propose new features or suggestions you can use the [Feedback Hub app in Edge](windows-feedback:?categoryid=5) (you will need Windows 10) and if you want to propose new web platform features you can use the [Microsoft Edge UserVoice](https://wpdev.uservoice.com/forums/257854-microsoft-edge-developer).

Thanks

**Comment by NitroRayZ** [comment]
Ok

**Comment by chirag127** [comment]
> if you want to propose new web platform features you can use the [Microsoft Edge UserVoice](https://wpdev.uservoice.com/forums/257854-microsoft-edge-developer).

This UserVoice instance is no longer available.

**Pull request closed without merging**
